export default [
  'Weighted crunch',
  'Weighted leg raise',
  'Dumbbell side bend',
  'Dumbbell bent over row',
  'Pulldown',
  'Wide-grip pulldown',
  'Cable fly',
  'Cable rear delta fly',
  'Rear delt fly',
  'Dumbbell fly',
  'Dumbbell bench press',
  'Barbell benchpress',
  'Closed grip barbell bench press',
  'Hyper extention/(back ectention)',
  'Calf raise',
  'Plank',
  'Side plank',
  'Crunch',
  'Cable curl',
  'Dumbbell curl',
  'Barbell curl',
  'Preacher curl',
  'Overhead triceps extention',
  'Triceps rope extention',
  'dip',
  'Reverse grip pullup',
  'Pullup ',
  'Oblique crunch',
  'Goblet squat',
  'Squat',
  'Sumo squat',
  'Deadlift',
  'Romanian deadlift',
  'Sumo deadlift',
  'Lunges',
  'Donkey kicks',
  'Hip thrust',
  'Bulgarian split squat',
  'Kettlebell swing',
  'Kettlebell one arm row',
  'Kettlebell one arm press',
  'Kettlebell shoulder halo',
  'Kettlebell hip halo',
  'Hip abduction',
  'Hip adduction'
]
